#!/usr/bin/env bash
#Copyright 2014 Thomas Elfström
#switchhub_status

# This file is part of SwitchHub.

# SwitchHub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SwitchHub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SwitchHub. If not, see <http://www.gnu.org/licenses/>.


RESULT="SwitchHub is running.\n"
ps aux|grep switchhub|grep -vE '(grep|switchhub_status)' >/dev/null||RESULT="SwitchHub is not running.\n"
printf "$RESULT"

ROWS=$(tail /var/log/switchhub.log | wc -l)
if [[ "$ROWS" > 0 ]]; then
    if (( "$ROWS" >= 10 )); then
        printf "The latest 10 log messages:\n"
    elif [[ "$ROWS" = 1 ]]; then
        printf "The latest log message:\n"
    else
        printf "The latest $ROWS log messages:\n"
    fi
    tail /var/log/switchhub.log
else
    printf "There is nothing in the log yet.\n"
fi



