#!/bin/bash

STATUS="on"
ps aux|grep switchhub|grep -vE '(grep|switchhub_start)' >/dev/null||STATUS="off"

if [ "$STATUS" == "on" ]; then
    printf "SwitchHub is already running.\n"
else
    #Manual detach (Ctrl+A D):
    screen /opt/switchhub/switchhub.py

    #Automatic detach:
    #screen -d -m /opt/switchhub/switchhub.py
fi
